name: interfaz_uno_aiq
description: A new Flutter project.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  signature: ^5.4.0
  pdf: ^3.10.8
  printing: ^5.12.0
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.2
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  shared_preferences: ^2.5.3
  image_picker: ^1.0.7
  syncfusion_flutter_pdfviewer: ^24.1.41
  file_picker: ^6.1.1
  excel: ^2.1.0
  slide_to_act: ^2.0.1
  open_file: ^3.3.2
  googleapis: ^13.1.0 
  googleapis_auth: ^1.4.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/AIQ_LOGO_.png
    - assets/Avion-one.png
    - assets/airbus.png
    - assets/derrames_form.png
    - assets/AIQ-OPS-F008-FORM-PREVIEW.jpg
    - assets/AIQ-OPS-F013-FORM-PREVIEW.jpg
    - assets/Avion-one.png
    - assets/AIQ-OPS-F007-FORM-PREVIEW.jpg
    - assets/AIQ-OPS-F005-FORM-PREVIEW.jpg
    - assets/PLANO_AIQ.pdf
    - assets/plano.png
    - assets/foto_random.jpg
    - assets/AIQ-AMB-F-004.jpg
    - assets/avionG.jpg
    - assets/generica.jpg

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/font/AvenirLTStd-Black.otf
