// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3c-mGGmvSoTsT2HDL4YCCGtAuNrDlYfY',
    appId: '1:411394758989:web:b535da78824b97071a7f04',
    messagingSenderId: '411394758989',
    projectId: 'aiq-forms',
    authDomain: 'aiq-forms.firebaseapp.com',
    storageBucket: 'aiq-forms.firebasestorage.app',
    measurementId: 'G-F1DJWXW2KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1uXI5hypVKVv-mtgEM8bCYuGewR0TzPQ',
    appId: '1:411394758989:android:4b699f74f5a282371a7f04',
    messagingSenderId: '411394758989',
    projectId: 'aiq-forms',
    storageBucket: 'aiq-forms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWfKy5upGN4kcTETlGboiRdaIUKlGVJmU',
    appId: '1:411394758989:ios:3e94de72a3e8378d1a7f04',
    messagingSenderId: '411394758989',
    projectId: 'aiq-forms',
    storageBucket: 'aiq-forms.firebasestorage.app',
    iosBundleId: 'com.example.aiqForms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWfKy5upGN4kcTETlGboiRdaIUKlGVJmU',
    appId: '1:411394758989:ios:3e94de72a3e8378d1a7f04',
    messagingSenderId: '411394758989',
    projectId: 'aiq-forms',
    storageBucket: 'aiq-forms.firebasestorage.app',
    iosBundleId: 'com.example.aiqForms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3c-mGGmvSoTsT2HDL4YCCGtAuNrDlYfY',
    appId: '1:411394758989:web:64d9f4cc1d9a8e8e1a7f04',
    messagingSenderId: '411394758989',
    projectId: 'aiq-forms',
    authDomain: 'aiq-forms.firebaseapp.com',
    storageBucket: 'aiq-forms.firebasestorage.app',
    measurementId: 'G-T9C007BNC0',
  );
}
